spring:
    security:
        oauth2:
            client:
                registration:
                    kakao:
                        redirect-uri: http://localhost:3000/login/kakaoAuthRedirect