spring:
    security: 
        oauth2:
            client:
                registration:
                    kakao:
                        redirect-uri: https://trip-chemistry-1-0.vercel.app/login/kakaoAuthRedirect
                        # redirect-uri: https://trip-chemistry.vercel.app/login/kakaoAuthRedirectgit stat