spring:
    data:
        mongodb: 
            uri: # Your MongoDB URI
            database: # Your MongoDB Database Name
    security: 
        oauth2:
            client:
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id
                registration:
                    kakao:
                        client-id: # Your Kakao API client id
                        client-secret: # Your Kakao API client secret
                        client-authentication-method: client_secret_post
                        authorization-grant-type: authorization_code
                        client-name: kakao
                        scope:
                        - profile_nickname
                        redirect-uri: # Your Kakao API redirect-uri